config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users, only: [:show,:edit,:update,:index, :destroy]
  resources :users do
    member do
      post 'follow' => 'users#follow'
      post 'unfollow' => 'users#unfollow'
      delete 'delete_avatar_attachment' => 'users#delete_avatar_attachment'

    end
  end
  resources :recipes do
    member do
        put 'like' => 'recipes#like'
        get 'board' => 'recipes#board'
        delete 'delete_picture_attachment' => 'recipes#delete_picture_attachment'
    end
    resources :comments

    
  end


  resources :comments, except: [:show,:index]

  root to: "recipes#index"
  resources :categories, only: [:show,:index]

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true
    has_many :comments, as: :commentable

    validates :body, presence: true, length: {minimum: 3, maximum: 150}

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create,:edit,:update,:destroy]
  before_action :set_comment, only: [:edit,:update,:destroy]
  before_action :require_same_user, only: [:edit,:update,:destroy]
  
  def new
    @comment = Comment.new
  end
  
  def create
    @commentable = Recipe.find(params[:recipe_id])
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to @commentable, notice: "Your comment was successfully posted."
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      flash[:notice]="Comment was updated successfully."
      if @comment.commentable_type == 'Recipe'
         @recipe = Recipe.find(@comment.commentable_id)
        redirect_to @recipe
      end
    else
      render 'edit'
    end
  end

  def destroy
    if @comment.commentable_type == 'Recipe'
        @recipe = Recipe.find(@comment.commentable_id)
      if @comment.destroy
        flash[:notice]= "Your comment was deleted."
      else
        flash[:danger]= "An error prevent your comment from being deleted."
      end
      redirect_back fallback_location: @recipe
    end
  end
  
  private
  
    def comment_params
      params.require(:comment).permit(:body)
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end
       
    def require_same_user
      if current_user != @comment.user
          flash[:alert] = "You can only edit or delete your own comment"
          if @comment.commentable_type == 'Recipe'
            @recipe = Recipe.find(@comment.commentable_id)
           redirect_to @recipe
         end
      end
    end

    def set_commentable
    end
    
end
    

app/views/comments/_comment.html.erb
<div class="row d-flex justify-content-center mt-100 mb-100 pb-3">
  <div class="col-9">
    <div class="card-body text-center">
        <h5 class="card-title"><%= pluralize(commentable.comments.size,'comment')%></h5>
    </div>
    <div class="comment-widgets ">
      <% commentable.comments.each do |comment|%>
      <div class="d-flex flex-row comment-row mt-0 mb-3 shadow-sm ">
        <div class="p-2">
          <% if comment.user.avatar.attached? %>
            <%= image_tag(comment.user.mini_avatar_thumbnail,alt: "Trust me I'm cool",class:"rounded-circle",width:"50",height:"50") %>
          <% else %>
            <%= image_tag("default.png", alt: "A smiling face", width: "50")%>
          <% end %>
        </div>
          <div class="comment-text w-100 p-2">
            <div class="d-flex">
            <h6><%= link_to comment.user.username,user_path(comment.user) ,class:"text-dark",style:"text-decoration:none;"%><br/></h6>
            </div>
            <div class="d-flex">
            <h7><%= comment.body%></h7>
            </div> 
            <div class="comment-footer text-right">
            <span class="pl-2 mt-0"><small><%=time_ago_in_words(comment.created_at)%> ago</small></span>

              <% if user_signed_in?  && (comment.user==current_user)%>
                <%= link_to "Edit", edit_comment_path(comment),class:"text-right text-info",style:"text-decoration:none;"%>
                <%= link_to "Delete", comment, method: :delete,class:"text-right text-danger", data: {confirm: "Are you sure?"},style:"text-decoration:none;" %>
              <% end %>
            </div>
          </div>
      </div> 
      <%end%>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="row d-flex justify-content-center mt-100 mb-100 p-20">
<div class="col-9">
<%= form_for [commentable,Comment.new] do |f| %>
    <div class="form-group">
    <%= f.text_area :body, class: "form-control", placeholder: "Add a comment", minlength:3,maxlength:150 %>
    </div>
    <%= f.submit "Submit", class: "btn btn-outline-info mb-3 btn" %>
<% end %>
</div>
</div>

app/views/comments/edit.html.erb
<h3 class="text-center mt-4"> Edit your comment </h3>

<div class="container mt-10">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= form_with(model: @comment,class:"shadow p-3 mb-3 rounded", local: true) do |f|%>
                <div class="form-group">
                <%= f.text_area :body, class:"form-control shadow rounded", minlength:3,maxlength:150  %>
                </div>
                <div class="form-group row justify-content-center">
                <%= f.submit class:"btn btn-outline-info btn-sm mt-3" %>
                </div>
            <%end%>
        </div>
    </div>
</div>