config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users, only: [:show,:edit,:update,:index, :destroy]
  resources :users do
    member do
      post 'follow' => 'users#follow'
      post 'unfollow' => 'users#unfollow'
      delete 'delete_avatar_attachment' => 'users#delete_avatar_attachment'

    end
  end
  resources :recipes do
    member do
        put 'like' => 'recipes#like'
        get 'board' => 'recipes#board'
        delete 'delete_picture_attachment' => 'recipes#delete_picture_attachment'
    end
    resources :comments

    
  end


  resources :comments, except: [:show,:index]

  root to: "recipes#index"
  resources :categories, only: [:show,:index]

end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_one_attached :picture
    has_many :recipe_categories
    has_many :categories, through: :recipe_categories
    acts_as_votable
    has_many :comments, as: :commentable,dependent: :destroy

    scope :of_followed_users, -> (following_users) { where user_id: following_users }

    
    validates :title,   presence: true,
                        length: {minimum: 5, maximum: 40}
    
    validates :prep_time,   presence: true,
                            numericality: { only_integer: true, greater_than: 0}
    
    validates :cook_time, numericality: {only_integer: true, allow_nil: true,greater_than: 0}

    validates :servings, numericality: {only_integer:true, greater_than: 0, allow_nil:true}

    validates :ingredients, presence:true,
                            length: {minimum: 10, maximum: 500} 

    validates :directions,  presence:true,
                            length: {minimum: 50, maximum: 2000}

    validates :notes, length: {maximum:100}

    validate :correct_picture_type

    def picture_thumbnail
        picture.variant(resize: "300x300!").processed
    end

    def self.search_by(search_term)
        where("lower(title) LIKE :search_term", search_term: "%#{search_term.downcase}%")
    end


    private

    def correct_picture_type
        if picture.attached? && !picture.content_type.in?(%w(image/jpeg image/png))
            errors.add(:picture,"must be PNG or JPEG.")
        end
        if picture.attached? && (picture.byte_size > 1.megabytes)
            errors.add(:picture,"maximum size is 1Mb")
        end    
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy,:like,:delete_picture_attachment]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy,:delete_picture_attachment]
  respond_to :js, :html, :json

  def show

  end
  
  def index
    @recipes=Recipe.order(:created_at).per_page_kaminari(params[:page])
    if params[:search]
        @search_term=params[:search]
        @recipes=@recipes.search_by(@search_term)
    end
  end

  def board
    @recipes= Recipe.of_followed_users(current_user.followees).order('created_at DESC').per_page_kaminari(params[:page])
  end

  
  def new 
    @recipe=Recipe.new
  end
  
  def edit
  end
  
  def create
    @recipe=Recipe.new(recipe_params)
    @recipe.user=current_user
    if @recipe.save
        flash[:notice]="Recipe was created successfully."
        redirect_to @recipe
    else
        render 'new'
    end
  end 
  
  def update
    if @recipe.update(recipe_params)
        flash[:notice]="Recipe was updated successfully."
        redirect_to @recipe
    else
        render 'edit'
    end
  end
  
  def destroy
    if @recipe.destroy
      flash[:notice]="Recipe was deleted successfully."
    else
      flash[:alert] = "An error prevent your recipe from being deleted."
    end
    redirect_to recipes_path
    
  end

  def like
    if params[:format] == 'like'
      @recipe.liked_by current_user
    elsif params[:format] == 'unlike'
      @recipe.unliked_by current_user 
    end
    redirect_back fallback_location: recipe_url
  end 

  def delete_picture_attachment
    if @recipe.picture.purge
      flash[:notice]="Picture was deleted successfully."
    else
      flash[:alert] = "An error prevent the image from being deleted."
    end
    redirect_to @recipe
  end

  private 
  
    def set_recipe
        @recipe = Recipe.find(params[:id])
    end
        
     def recipe_params
        params.require(:recipe).permit(:title,:prep_time,:cook_time,:servings,:directions,:ingredients,:notes,:picture,category_ids: [])
    end

    def require_same_user
      if current_user != @recipe.user
        flash[:alert] = "You can only edit or delete your own recipe"
        redirect_to @recipe
      end
    end

end

app/views/recipes/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @recipe%>
            <%= form_with(model: @recipe,class:"shadow p-3 mb-3 rounded", local: true) do |f|%>


                <div class="form-group row">
                    <%= f.label :title, class:"col-2 col-form-label text-dark" %>
                    <div class="col-10">
                        <%= f.text_field :title, class:"form-control shadow rounded",maxlength:40 %>
                    </div>    
                </div>

                <div class="form-group row">
                    <%= f.label :servings, class:"col-2 col-form-label text-dark" %>
                    <div class="col-10">
                        <%= f.number_field :servings, class:"form-control shadow rounded", min:1 %>
                    </div>    
                </div>
                <div class="form-group row">
                    <%= f.label :prep_time, class:"col-2 col-form-label text-dark" %>
                    <div class="col-10">
                        <%= f.number_field :prep_time, class:"form-control shadow rounded", min:1 %> minutes
                    </div>    
                </div>
                <div class="form-group row">
                    <%= f.label :cook_time, class:"col-2 col-form-label text-dark" %>
                    <div class="col-10">
                        <%= f.number_field :cook_time, class:"form-control shadow rounded",min:0 %> minutes
                    </div>    
                </div>
                <div class="form-group row">
                    <%= f.label :ingredients, class:"col-2 col-form-label text-dark" %>
                    <div class="col-10">
                        <%= f.text_area :ingredients,rows:8, class:"form-control shadow rounded",maxlength:500%>
                    </div>    
                </div>
                <div class="form-group row">
                    <%= f.label :directions, class:"col-2 col-form-label text-dark" %>
                    <div class="col-10">
                        <%= f.text_area :directions,rows:10, class:"form-control shadow rounded",maxlength:2000 %>
                    </div>    
                </div>
                <div class="form-group row">
                    <%= f.label :category, class: "col-2 col-form-label text-dark" ,id:"category"%>
                    <div class="col-10"> 
                        <%= f.collection_select(:category_ids, Category.all, :id, :name,
                        { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :notes, class:"col-2 col-form-label text-dark" %>
                    <div class="col-10">
                        <%= f.text_area :notes,rows:3, class:"form-control shadow rounded",maxlength:100 %>
                    </div>    
                </div>
                
                <div class="form-group row" >
                    <div class="row justify-content-center">
                    <%= image_tag(@recipe.picture,width: "150",height: "150") if @recipe.picture.attached?%>
                    </div>
                </div>

                <div class="form-group row">
                    <%= f.label :picture, class:"col-2 col-form-label text-dark" %>
                    <%= f.file_field :picture,class:"col-2 col-form-label text-dark" %>

                </div>


                
                <div class="form-group row justify-content-center">
                    <%= f.submit class:"btn btn-outline-info btn-m mt-3" %>
                </p>

            <% end %>
        </div>

    </div>
</div>

app/views/recipes/_recipe.html.erb
<div class="container">
<% @recipes.each do |recipe| %>
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header font-italic">
                     by <%= link_to recipe.user.username, user_path(recipe.user),:class=>"text-dark",style:"text-decoration:none;" %>
                </div>
                <div class="card-body">
                    <h5 class="card-title" id="title-recipe"><%= link_to recipe.title, recipe_path(recipe), class:"text-success",style:"text-decoration:none;" %></h5>
                    <div>
                    <% if  recipe.categories.any? %>
                        <div class="mt-2 mb-1"><%= render recipe.categories %></div>
                    <%end%>
                    </div>
                    <div>
                    <% if recipe.picture.attached? %>
                        <%= image_tag(recipe.picture,width:"250",height:"250") %>
                    <% end %>
                    </div>

                    <div class="mt-3">
                    <p class="card-text">
                    <% if recipe.servings %>
                        <%= recipe.servings %> servings | 
                    <%end%>
                    Preparation time: <%= recipe.prep_time%> minutes 
                    <% if recipe.cook_time?%> 
                     | Cooking time: <%= recipe.cook_time%> minutes 
                    <%end %></p>
                    </div>
                    <p class="card-text mt-3"><%=  truncate(recipe.directions,length:100)%></p>
                    <%= link_to "View", recipe_path(recipe), class: "btn btn-outline-success",style:"text-decoration:none;" %>
                    <% if user_signed_in? && (recipe.user == current_user) %>
                    <%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-outline-info",style:"text-decoration:none;" %>
                    <%= link_to "Delete", recipe_path(recipe), class: "btn btn-outline-danger",style:"text-decoration:none;", method: :delete, data: {confirm: "Are you sure?"} %>
                    <% end%>
                </div>
                <div class="card-footer text-muted">
                    <small> Created <%=time_ago_in_words(recipe.created_at)%> ago,
                        Updated <%=time_ago_in_words(recipe.updated_at)%> ago </small>
                    </div>
                </div>
                 
            </div>
        </div>
    <% end %>

</div>

app/views/recipes/board.html.erb
<% if @recipes.count == 0%>
    <div class="text-center mt-5">
    <h5> Your dashboard is empty, try some delicious <%= link_to "recipes", recipes_path,class:"o-link"%> 
    or discover some amazing <%= link_to "bloggers", users_path,class:"p-link"%></h5>
    </div>
<%else%>
    <%= paginate @recipes %>
    <%= render 'recipe' %>
    <%= paginate @recipes%>
<%end%>

app/views/recipes/edit.html.erb
<h2 class="text-center mt-4"> Edit recipe </h2>

<%= render 'form', recipe: @recipe %>

app/views/recipes/index.html.erb
  
<h1 class="text-center mt-4">
  <% if params[:search] && @recipes.count!= 0%>
    <%= pluralize(@recipes.count,'recipe')%> found for <%=@search_term.downcase%>
  <%elsif params[:search] && @recipes.count== 0%>
    No recipes found for <%=@search_term.downcase%>
  <%else%>
    Recipes
  <%end%>
</h1>
  <%= paginate @recipes %>
    <%= render 'recipe' %>
  <%= paginate @recipes%>

app/views/recipes/new.html.erb
<h2 class="text-center mt-4"> Create new recipe </h2>
<%= render 'form' %>

app/views/recipes/show.html.erb
<h2 class="text-center mt-4"><%= @recipe.title%></h2>
<div class="container pb-5">
    <div class="row justify-content-md-center">
        <div class="col-12 mt-4">
            <div class="card text-center shadow  bg-white rounded">
                <div class="card-header font-italic">
                     by <%= link_to @recipe.user.username, user_path(@recipe.user),:class=>"text-dark", style:"text-decoration:none;" %>
                  </div>
                <div class="card-body">
                    <div>
                        <% if  @recipe.categories.any? %>
                            <div class="mt-2"><%= render @recipe.categories %></div>
                        <%end%>
                    </div>
                    <div class="mt-2">
                        <% if @recipe.picture.attached? %>
                            <%= image_tag(@recipe.picture,width:"auto",height:"350") %>
                        <% end %>

                    </div>
                    <div class="mt-1">
                        <% if user_signed_in? && current_user == @recipe.user && @recipe.picture.attached?%>
                            <%= link_to  delete_picture_attachment_recipe_url(@recipe), method: :delete, data: { confirm: 'Are you sure?' } do %>
                                <button class="btn btn-outline-danger btn-sm"><i class="fas fa-trash"></i></button>
                            <%end%>
                        <%end%>
                    </div>
  

                    <div class="mt-3">
                   
                    <h6>
                        <p class="card-text">
                        <% if @recipe.servings %>
                            <%= @recipe.servings %> servings | 
                        <%end%>
                         Preparation time: <%= @recipe.prep_time%> minutes 
                        <% if @recipe.cook_time?%> 
                        | Cooking time: <%= @recipe.cook_time%> minutes 
                        <%end %></p>
                    </h6>
                    </div>
                    <br/>
                    <div class="card-text text-left"><h6>Ingredients:</h6><%=simple_format(@recipe.ingredients)%></div><br/>
                    <div class="card-text text-left"><h6>Directions:</h6><%=simple_format(@recipe.directions)%></div>
                    <% if @recipe.notes? %>
                        <div class="card-text text-left"><h6>Notes:</h6><%=simple_format(@recipe.notes)%></div>
                    <%end %>
                    <% if user_signed_in? && (current_user == @recipe.user)%>
                    <%= link_to "Edit", edit_recipe_path(@recipe), class: "btn btn-outline-info btn" %>
                    <%= link_to "Delete", recipe_path(@recipe), class: "btn btn-outline-danger btn", method: :delete, data: {confirm: "Are you sure?"} %>
                    <% end%>
                </div>

                <div>
                    <span class='parent-likes'>
                        <%=pluralize( @recipe.get_likes.size,'like')%> </br>
                        <%if user_signed_in?%>
                        <%if current_user.liked?  @recipe%>
                            <div> <%= link_to like_recipe_path(@recipe,'unlike'),class:"unlike-btn", style:"text-decoration:none;",method: :put, remote: :true do %><i class="fas fa-heart fa-2x" id="full-heart" style="color:red"></i>
                            </div>
                            <%end%>
                        <%else%>
                            <div> <%= link_to like_recipe_path(@recipe,'like'),class:"like-btn", style:"text-decoration:none;",method: :put, remote: :true do %><i class="far fa-heart fa-2x" id="empty-heart" style="color:red"></i>
                            </div>
                            <%end%>
                        <%end%>
                        <%end%>
                    </span>
                    </div>

                <div class="card-footer">
                </div>
                <%= render partial: 'comments/comment', locals: {commentable: @recipe }%>
                <% if user_signed_in? %>
                    <%= render partial: "comments/form", locals: {commentable: @recipe} %>
                <% end %>


            </div>
            
        </div>
      
    </div>
</div>              