config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users, only: [:show,:edit,:update,:index, :destroy]
  resources :users do
    member do
      post 'follow' => 'users#follow'
      post 'unfollow' => 'users#unfollow'
      delete 'delete_avatar_attachment' => 'users#delete_avatar_attachment'

    end
  end
  resources :recipes do
    member do
        put 'like' => 'recipes#like'
        get 'board' => 'recipes#board'
        delete 'delete_picture_attachment' => 'recipes#delete_picture_attachment'
    end
    resources :comments

    
  end


  resources :comments, except: [:show,:index]

  root to: "recipes#index"
  resources :categories, only: [:show,:index]

end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :recipes, dependent: :destroy
  acts_as_voter
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users, dependent: :destroy
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validate :correct_avatar_type



  validates :username,  presence: true,
                          uniqueness: {case_sensitive: false},
                          length: {minimum:3, maximum:25}
  validates :bio, length: {maximum:160}
  
  def avatar_thumbnail
    avatar.variant(resize: "250x250",gravity: "center").processed
  end
  def mini_avatar_thumbnail
    avatar.variant(resize: "100x100",gravity: "center").processed
  end


  private

  def correct_avatar_type
    if avatar.attached? && !avatar.content_type.in?(%w(image/jpeg image/png))
      errors.add(:avatar,"must be PNG or JPEG.")
    end
    if avatar.attached? && (avatar.byte_size > 1.megabytes)
      errors.add(:avatar,"maximum size is 1Mb")
    end
  end


  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    before_action :set_user, except: [:index]
    before_action :authenticate_user!, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy,:delete_avatar_attachment]

    def show
        @recipes = @user.recipes.per_page_kaminari(params[:page])
    end

    def index
        @users=User.order(:username).per_page_kaminari(params[:page])    
    end
    
    def edit
    end


    def update
        if @user.update(user_params)
            flash[:notice]="Your account information was successfully updated"
            redirect_to @user
        else
            render 'edit'
        end

    end

    def destroy
        if @user.destroy
            flash[:notice] = "Your account was successfully deleted"
        else
            flash[:alert] = "An error prevent your account from being deleted."
        end
        redirect_to root_path

    end

    def follow
        @user = User.find(params[:id])
        current_user.followees << @user
        redirect_back(fallback_location: user_path(@user))
    end
      
    def unfollow
        @user = User.find(params[:id])
        current_user.followed_users.find_by(followee_id: @user.id).destroy
        redirect_back(fallback_location: user_path(@user))
    end

    def delete_avatar_attachment
        if @user.avatar.purge
            flash[:notice] = "Avatar was deleted successfully."
        else
            flash[:danger] = "An error prevent your avatar from being deleted."
        end
        redirect_to @user
    end
    
    

    private
        #whitelist
        def user_params
            params.require(:user).permit(:username, :email, :password,:avatar,:username,:bio)
        end

        def set_user
            @user=User.find(params[:id])
        end
        def require_same_user
            if current_user != @user 
            flash[:alert] = "You can only edit or delete your own account"
            redirect_to @user
            end
        end
end

app/views/users/_form.html.erb
<div class="container ">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @user%>
            <%= form_with(model: @user,class:"shadow p-3 mb-3 rounded", local: true) do |f|%>

                <div class="form-group row" >
                    <div class="row justify-content-center">
                    <%= image_tag(@user.avatar,class:"rounded-circle",width: "200",height: "200") if @user.avatar.attached?%>
                    </div>
                </div>

                <div class="form-group row"  >
                   <%= f.label :avatar, class:"col-2 col-form-label text-dark" %>
                    <%= f.file_field :avatar,class:"col-2 col-form-label text-dark" %>
                </div>

                <div class="form-group row">
                    <%= f.label :username, class:"col-2 col-form-label text-dark" %>
                    <div class="col-10">
                        <%= f.text_field :username, class:"form-control shadow rounded",placeholder:"Enter a username" %>
                    </div>    
                </div>

                <div class="form-group row">
                    <%= f.label :bio, class:"col-2 col-form-label text-dark" %>
                    <div class="col-10">
                        <%= f.text_area :bio, class:"form-control shadow rounded",placeholder:"Enter a bio" %>
                    </div>    
                </div>
 
                <div class="form-group row justify-content-center text-dark">
                    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class:"btn btn-outline-info btn-m mt-3" )%>
                </p>

            <% end %>
        </div>
        <div class="mb-3">
        </div> 
    </div>
</div>


 

app/views/users/_user.html.erb
<div class="container">
<% @users.each do |user| %>
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header font-italic">
                    <%= link_to user.username, user,:class=>"text-dark", :style=>"text-decoration:none;font-size:20px;"%>
                </div>
                <div class="row justify-content-md-center">
           
                <div style="width:400px; height:auto" class="mt-4">
                    <% if user.avatar.attached? %>
                    <%= image_tag(user.avatar,class:"rounded-circle",width: "200",height:"200") %>
                    <% else %>
                        <%= image_tag("default.png", alt: "A smiling face", width: "300")%>
                    <% end %>
                </div>
       
                </div>
                <div class="card-body mb-4">
                    <p class="card-text"><%= pluralize(user.recipes.count, "post")%> |
                    <%= pluralize(user.followers.count, "follower")%> |
                    <%= user.followees.count%> followed </p> 
                    <div class="mt-2">
                    <h4><%= user.bio %></h4>
                    </div>

                </div>


                <div class="card-footer text-muted">
                    <small> Joined <%=time_ago_in_words(user.created_at)%> ago </small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<h2 class="text-center mt-4"> Edit your profile </h2>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4"> Food Bloggers </h1>


<%= paginate @users %>
<%= render 'user' %>
<%= paginate @users %>

app/views/users/show.html.erb
<div class="text-center mt-4">
  <h1 class="text-center mt-4"><%= @user.username%>'s profile</h1>
  <% if user_signed_in? && @user == current_user %>
    <div class="text-center mt-2 mb-2">
      <%= link_to "Edit", edit_user_path(@user), class: "btn btn-outline-info btn-sm" %>
      <%= link_to "New recipe", new_recipe_path, class: "btn btn-outline-info btn-sm",id: "new-btn" %>
    </div>
  <% end %>
  <div>
    <% if @user.avatar.attached? %>
      <%= image_tag(@user.avatar,class:"rounded-circle",width: "300",height:"300") %>
    <% else %>
      <%= image_tag("default.png", alt: "A smiling face", width: "300")%>
    <% end %>
  </div>
  <div class="mt-1">
    <% if user_signed_in? && current_user == @user && @user.avatar.attached?%>
      <%= link_to  delete_avatar_attachment_user_url(@user), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <button class="btn btn-outline-danger btn-sm"><i class="fas fa-trash"></i></button>
      <%end %>
    <%end%>
  </div>

    <section class="mt-4" id="all-links">
      <p>
      <%= @user.followers.size%> followers
      <%= @user.followees.size%> followed
      <% if user_signed_in? && current_user != @user %>
        <% if current_user.followees.include?(@user) %>
            <h5><%=link_to "Unfollow", unfollow_user_path, method: :post, class: "btn btn-outline-info",style:"text-decoration:none;",id:"unfollow-btn"%></h5>
        <% else  %>
            <h5><%=link_to "Follow", follow_user_path, method: :post, class: "btn btn-outline-info",style:"text-decoration:none;",id:"follow-btn"%></h5>
        <% end%>
      <%end%>
      </p>
  </section>
</div>
<h3 class="text-center"> <%= @user.bio%> </h3>
 
<h3 class="text-center mt-5"> Recipes </h3>
<%= paginate @recipes %>
<%= render 'recipes/recipe' %>
<%= paginate @recipes%>