config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users, only: [:show,:edit,:update,:index, :destroy]
  resources :users do
    member do
      post 'follow' => 'users#follow'
      post 'unfollow' => 'users#unfollow'
      delete 'delete_avatar_attachment' => 'users#delete_avatar_attachment'

    end
  end
  resources :recipes do
    member do
        put 'like' => 'recipes#like'
        get 'board' => 'recipes#board'
        delete 'delete_picture_attachment' => 'recipes#delete_picture_attachment'
    end
    resources :comments

    
  end


  resources :comments, except: [:show,:index]

  root to: "recipes#index"
  resources :categories, only: [:show,:index]

end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-dark-50">
    <div class="container text-center text-dark">
        <small> by &copy;<%= link_to "Giulia Mazzucchelli", "https://www.linkedin.com/in/giulia-mazzucchelli-472487182/", class:"text-dark"%> </small>
       <br> 
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container col-4">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible mt-3 fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="nav-bar-brand">
    <%= link_to root_path do %>
    <%= image_tag("logo.png",width:"100%",class:"mb-3") %>
    <%end%>
  </div>  
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span> </button>
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to "Bloggers", users_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Categories", categories_path,id:"nav-categories", class: "nav-link" %>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Recipes
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "View Recipes",recipes_path, class: "dropdown-item" %>
        <% if user_signed_in? %>
          <%= link_to "Wall", board_recipe_path(current_user), class: "dropdown-item"%>
          <%= link_to "New recipe", new_recipe_path, class: "dropdown-item" %>
        <% end %>  
      </div>
    </li>
    <li class="nav-item">
    <div class="form-group col-1">
    <%= form_for "",url: recipes_path,class:"form-control col-7", role: "search",id:"search",method: :get do%>
    <%= text_field_tag :search, @search_term, placeholder: "Search recipes..."%>
    <% end%>
    </div>
    </li>

    </ul>

  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item ml-auto dropdown ">
          <a class="nav-link  dropdown-toggle" href="#" id="navbarDropdown-user" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit you profile", edit_user_path(current_user), class: "dropdown-item" ,id: "dropdown-editprofile"%>
            <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete,id: "dropdown-logout" %>
            <%= link_to "Delete account", user_path(current_user), class: "dropdown-item text-danger",id:"dropdown-delete",method: :delete, data: { confirm: "Are you sure?" },id: "dropdown-delete" %> 
          </div>
        </li>
      <% elsif admin_signed_in?%>
        <%= link_to "Admin page", rails_admin.dashboard_path, class: "nav-link" %>
      <%else %>
        <li class="nav-item ml-auto dropdown ">
          <a class="nav-link  dropdown-toggle" href="#" id="navbarDropdown-user" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Log in
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "User", new_user_session_path, class: "dropdown-item" %>
            <%= link_to "Admin", new_admin_session_path, class: "dropdown-item"%>

          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
        </li> 
      <%end%>
    </ul>
  </div>


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodiegramBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column" >
    <%= render 'layouts/navigation'%>
    <div id="page-content">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
      <%= render 'layouts/footer'%>
  </body>
</html>